[package]
name = "axum-demo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["full"] }
